### ISSUE TITLE
[Dataset] Cannot recover the demonstrations in the demonstration dataset

### ISSUE THREAD

**Issue by xavihart** [FrankZheng2022/PRISE#1]
I am using this simple code snippet to recover the actions in the training demonstration dataset, and here I encountered two problems:
-  The rolling results of the ground-truth actions do not match with the ground-truth observations in the dataset, is it due to some randomness?
- The observations during the rolling have a green line, how can I remove that

```
import warnings
warnings.filterwarnings('ignore', category=DeprecationWarning)

import torch
import numpy as np
import utils.libero_wrapper as libero_wrapper
from libero.libero import benchmark
import cv2
from replay_buffer import make_replay_loader_dist, ReplayBuffer
from pathlib import Path
from skvideo.io import vwrite


task_id = 0
benchmark_dict = benchmark.get_benchmark_dict()
task_suite = benchmark_dict['libero_10']()
task = task_suite.get_task(task_id)
task_name = task.name
libero_env = libero_wrapper.make(
                           task_id=task_id,
                           task_suite_name='libero_10',
                           libero_path='/ssdscratch/hxue45/data/tmp/PRISE/LIBERO'
                         )

offline_data_dir = construct_task_data_path(data_storage_dir, task_name, '_framestack1')
data_iter = [i for i in offline_data_dir.glob("*.npz")]
data_iter.sort()

for data in data_iter:
    data_ = np.load(data)
    action = data_['action']
    vwrite('demo_gt.mp4', data_['observation'].transpose(0, 2, 3, 1)[:, ::-1, :, :])
    print(action.shape)
    agent_view_list = []
    for i in range(action.shape[0]):
        act = action[i]
        agentview = libero_env.step(act).agentview
        agent_view_list.append(agentview)
    vwrite('demo.mp4', np.stack(agent_view_list).transpose(0, 2, 3, 1)[:, ::-1, :, [2, 1, 0]])
```

**Comment by FrankZheng2022** [comment]
Thanks for checking out our code. 
Regarding the first question, I don't quite understand what you mean by "results of the ground-truth actions do not match with the ground-truth observations". But it might be related to the specific way that we store the data. In the current replay buffer (which is adapted from DrQ-v2's replay buffer), the states/observations are stored as [s_0,s_1,..., s_T], [0,a_0,..., a_{T-1}]. So there is a mismatch by 1.  Observation at index i corresponds to the action at index i+1. I am not sure whether your question is related to this.
For the second question, you mean the image rendered from the simulator has a green line in it?

**Comment by xavihart** [comment]
For question one:
I just load the actions from one trajectory from the demonstration dataset, (a_1, a_2, ...) and then reset the env, running the actions one by one. I found that it cannot perfectly complete the task.


For question two:

<img width="507" alt="image" src="https://github.com/FrankZheng2022/PRISE/assets/46107454/430e3d47-3b6e-4f59-bf8b-7b29e1226a9e">

**Comment by FrankZheng2022** [comment]
For your first question, how do you choose the initial state? The initial state are sampled from a fixed set, and for now I don't think there is a way to recover the initial state from the official demonstration episodes provided by LIBERO.
For the second question, this is quite strange. I don't think I have encountered this problem during rollout, but let me look into this issue and get back to you once I have an answer to it.

**Comment by xavihart** [comment]
I fixed the second question, the problem is that I missed the env.reset().

For the first question, I reset the env using libero_wrapper.make provided in `utils/libero_wrapper.py`, and when I ran the actions many times, the results were always different, I am curious whether (1) the initial states introduce randomness or (2) the real actions operated include randomness (e.g. random noise)

**Comment by FrankZheng2022** [comment]
I think it is the randomness of the initial states. Currently the reset function of the wrapper I write samples one initial state out of a set of 50 initials states. But I cannot recover the exact initial state from the human demonstrations provided by the official LIBERO codebase. This part (how to recover the exact initial state) is missing in their official documentation.

**Comment by xavihart** [comment]
Got it. Thanks again for your careful reply.
