### ISSUE TITLE
RuntimeError: The size of tensor a (4) must match the size of tensor b (69) at non-singleton dimension 2

### ISSUE THREAD

**Issue by BrightMoonStar** [FrankZheng2022/PRISE#3]
When I ran this case, I encountered the following error. Can you help me? Thank you!
Stage III: Downstream Adaptation:
Case I: Multitask Learning: To train a multitask generalist policy on LIBERO-90:
`python train_prise.py exp_name=${EXP_NAME} replay_buffer_num_workers=4 stage=3 exp_bc_name=${DOWNSTREAM_EXP_NAME} multitask=true downstream_task_suite=libero_90 num_train_steps=30010 eval=false save_snapshot=true vocab_size=${VOCAB_SIZE} &`

```
Resuming Snapshopt
========= Tokenizing the downstream data... ==========
Error executing job with overrides: ['exp_name=./experiments/run_0', 'replay_buffer_num_workers=0', 'stage=3', 'multitask=true', 'downstream_task_suite=libero_90', 'num_train_steps=30010', 'eval=false', 'save_snapshot=true', 'vocab_size=200']
Traceback (most recent call last):
  File "train_prise.py", line 447, in main
    workspace.downstream_adapt()
  File "/home/a/Videos/bin/boot/PRISE/train_prise.py", line 329, in downstream_adapt
    u = self.agent.PRISE.module.action_encoder(z, action.float())
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a/Videos/bin/boot/PRISE/prise_agent.py", line 71, in forward
    return self.sa_embedding(z.detach()+u)
RuntimeError: The size of tensor a (4) must match the size of tensor b (69) at non-singleton dimension 2

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by BrightMoonStar** [comment]
Hi~
 I've spent a long time today trying to solve this problem but still haven't succeeded, if you could give me some guidance I'd really appreciate it!

**Comment by FrankZheng2022** [comment]
Hi, thanks for your question. Indeed there was an error in our original code. In the original code, ``z = self.agent.compute_transformer_embedding(z)`` is missing. Thus the ``z`` there has not been passed through the transformer layer. This has been fixed now. 
Feel free to ask if you have any other questions about the code, and we will be more than happy to address them. Thanks again!

**Comment by BrightMoonStar** [comment]
Thanks for your help！And I find another issue and provide it for you . In following function,  `return cls ` may be missing. Thanks again!
```
def register_benchmark(cls):
    BENCHMARK_MAPPING[cls.__name__.lower()] = cls
    return cls  
```
